/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cmu.ri.airboat.client.gui;

import edu.cmu.ri.crw.data.UtmPose;
import robotutils.Pose3D;

/**
 *
 * @author okhwaja
 */
public class PrimitivesPanel extends AbstractAirboatPanel {
    
    /**
     * Creates new customizer PrimitivesPanel
     */
    public PrimitivesPanel() {
        initComponents();
    }
    public void update()
    {
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Send = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        firstAngle = new javax.swing.JTextField();
        secondAngle = new javax.swing.JTextField();
        firstDuration = new javax.swing.JTextField();
        secondDuration = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fourthDuration = new javax.swing.JTextField();
        thirdAngle = new javax.swing.JTextField();
        thirdDuration = new javax.swing.JTextField();
        thirdThrust = new javax.swing.JTextField();
        fourthAngle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        firstThrust = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        secondThrust = new javax.swing.JTextField();
        fourthThrust = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jLabel1.setText("Angle: [30, 150]");

        jLabel2.setText("Angle: [30, 150]");

        jLabel3.setText("Duration: >0 sec");

        jLabel4.setText("Duration: >0 sec");

        Send.setText("Send");
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        jLabel5.setText("Primitives Panel");

        firstAngle.setText("0");

        secondAngle.setText("0");

        firstDuration.setText("0");

        secondDuration.setText("0");

        jLabel6.setText("Angle: [30, 150]");

        fourthDuration.setText("0");

        thirdAngle.setText("0");

        thirdDuration.setText("0");

        thirdThrust.setText("0");

        fourthAngle.setText("0");

        jLabel7.setText("Third:");

        jLabel8.setText("First:");

        jLabel9.setText("Thrust: [1000, 2200]");

        firstThrust.setText("0");
        firstThrust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstThrustActionPerformed(evt);
            }
        });

        jLabel10.setText("Second:");

        jLabel11.setText("Thrust: [1000, 2200]");

        secondThrust.setText("0");

        fourthThrust.setText("0");

        jLabel12.setText("Duration: >0 sec");

        jLabel13.setText("Thrust: [1000, 2200]");

        jLabel14.setText("Fourth:");

        jLabel15.setText("Angle: [30, 150]");

        jLabel16.setText("Duration: >0 sec");

        jLabel17.setText("Thrust: [1000, 2200]");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel8)
                                .add(290, 290, 290)
                                .add(jLabel10))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(layout.createSequentialGroup()
                                                .add(21, 21, 21)
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .add(jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(31, 31, 31))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel12)
                                            .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel13))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(firstThrust, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                            .add(firstDuration)
                                            .add(firstAngle))
                                        .add(18, 18, 18)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel2)
                                            .add(jLabel11)
                                            .add(layout.createSequentialGroup()
                                                .add(37, 37, 37)
                                                .add(jLabel14))))
                                    .add(layout.createSequentialGroup()
                                        .add(thirdThrust, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18)
                                        .add(jLabel17))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, thirdAngle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, thirdDuration))
                                        .add(18, 18, 18)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel15)
                                            .add(jLabel16))))
                                .add(27, 27, 27)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(fourthDuration, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .add(secondDuration)
                                    .add(secondAngle)
                                    .add(secondThrust)
                                    .add(fourthAngle)
                                    .add(fourthThrust)))))
                    .add(layout.createSequentialGroup()
                        .add(239, 239, 239)
                        .add(jLabel5)))
                .addContainerGap(13, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(Reset)
                .add(236, 236, 236)
                .add(Send)
                .add(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(jLabel10))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(firstAngle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(firstDuration, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(8, 8, 8)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(firstThrust)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(secondAngle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(secondDuration, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(secondThrust, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel11))
                        .add(33, 33, 33)))
                .add(37, 37, 37)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jLabel14))
                .add(8, 8, 8)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(thirdAngle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(fourthAngle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel15))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(thirdDuration, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(fourthDuration, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12)
                    .add(jLabel16))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(thirdThrust, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(fourthThrust, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13)
                    .add(jLabel17))
                .add(31, 31, 31)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Send)
                    .add(Reset)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        // TODO add your handling code here:
        if (_vehicle == null)
        {
            firstAngle.setText(String.valueOf(-2));
            secondAngle.setText(String.valueOf(-2));
            thirdAngle.setText(String.valueOf(-2));
            fourthAngle.setText(String.valueOf(-2));
            
            firstDuration.setText(String.valueOf(-2));
            secondDuration.setText(String.valueOf(-2));
            thirdDuration.setText(String.valueOf(-2));
            fourthDuration.setText(String.valueOf(-2));
            
            firstThrust.setText(String.valueOf(-2));
            secondThrust.setText(String.valueOf(-2));
            thirdThrust.setText(String.valueOf(-2));
            fourthThrust.setText(String.valueOf(-2));
            
        }
        else
        {            
               double _firstAngle = Double.parseDouble(firstAngle.getText());
               double _secondAngle = Double.parseDouble(secondAngle.getText());
               double _thirdAngle = Double.parseDouble(thirdAngle.getText());
               double _fourthAngle = Double.parseDouble(fourthAngle.getText());
               
               
               
               double _firstDuration = Double.parseDouble(firstDuration.getText());
               double _secondDuration = Double.parseDouble(secondDuration.getText());
               double _thirdDuration = Double.parseDouble(thirdDuration.getText());
               double _fourthDuration = Double.parseDouble(fourthDuration.getText());
               
               
               
               double _firstThrust = Double.parseDouble(firstThrust.getText());
               double _secondThrust = Double.parseDouble(secondThrust.getText());
               double _thirdThrust = Double.parseDouble(thirdThrust.getText());
               double _fourthThrust = Double.parseDouble(fourthThrust.getText());
               
               Pose3D first = new Pose3D(_firstAngle, _firstDuration,
                       _firstThrust, 0, 0, 0);
               Pose3D second = new Pose3D(_secondAngle, _secondDuration, _secondThrust,
                       0, 0, 0);
               Pose3D third = new Pose3D(_thirdAngle, _thirdDuration, _thirdThrust,
                       0, 0, 0);
               Pose3D fourth = new Pose3D(_fourthAngle, _fourthDuration, _fourthThrust,
                       0, 0, 0);
               
               UtmPose[] command = {new UtmPose(first, UtmPose.DEFAULT_ORIGIN),                   
               new UtmPose(second, UtmPose.DEFAULT_ORIGIN), new UtmPose(third,
                       UtmPose.DEFAULT_ORIGIN), new UtmPose(fourth, UtmPose.DEFAULT_ORIGIN)};
               
               _vehicle.startWaypoints(command, "PRIMITIVES", null);
               
        }
        
        
            
        
    }//GEN-LAST:event_SendActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        firstAngle.setText(String.valueOf(0));
        secondAngle.setText(String.valueOf(0));
        thirdAngle.setText(String.valueOf(0));
        fourthAngle.setText(String.valueOf(0));
        
        firstDuration.setText(String.valueOf(0));
        secondDuration.setText(String.valueOf(0));
        thirdDuration.setText(String.valueOf(0));
        fourthDuration.setText(String.valueOf(0));
        
        firstThrust.setText(String.valueOf(0));
        secondThrust.setText(String.valueOf(0));
        thirdThrust.setText(String.valueOf(0));
        fourthThrust.setText(String.valueOf(0));
    }//GEN-LAST:event_ResetActionPerformed

    private void firstThrustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstThrustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstThrustActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton Send;
    private javax.swing.JTextField firstAngle;
    private javax.swing.JTextField firstDuration;
    private javax.swing.JTextField firstThrust;
    private javax.swing.JTextField fourthAngle;
    private javax.swing.JTextField fourthDuration;
    private javax.swing.JTextField fourthThrust;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField secondAngle;
    private javax.swing.JTextField secondDuration;
    private javax.swing.JTextField secondThrust;
    private javax.swing.JTextField thirdAngle;
    private javax.swing.JTextField thirdDuration;
    private javax.swing.JTextField thirdThrust;
    // End of variables declaration//GEN-END:variables
}
