/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataDisplayPopup.java
 *
 * Created on Nov 14, 2011, 5:04:59 PM
 */
package edu.cmu.ri.airboat.enduser;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pscerri
 */
public class DataDisplayPopup extends javax.swing.JFrame {

    DataDisplay dp = null;
    JPanel imgP = new JPanel() {

        public void paint(Graphics g) {
            int index = selectionCB.getSelectedIndex();
            BufferedImage img = dp.makeBufferedImage(index);
            int width = displayP.getWidth();
            int height = displayP.getHeight();
            g.drawImage(img, 0, 0, width, height, this);
        }

        @Override
        public Dimension getPreferredSize() {
            return new Dimension(400, 400);
        }
    };

    /** Creates new form DataDisplayPopup */
    public DataDisplayPopup(DataDisplay dataDisplay) {

        // @todo Another hack to fix when doing DataDisplay properly
        
        // @todo Paul removed data diaplay from here
        // dp = BoatSimpleProxy.dataDisplay;

        this.dp = dataDisplay;
        
        if (dp == null || dp.locInfo == null || dp.locInfo.size() == 0) {
            System.out.println("No data yet " + dp + " " + (dp != null? dp.locInfo.toString() : "null"));
            JOptionPane.showMessageDialog(null, "No sensor data available, try again after boats return data", "No available data", JOptionPane.OK_OPTION);
            return;
        }

        initComponents();

        xCountS.setValue(dp.getxCount());
        yCountS.setValue(dp.getyCount());

        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < dp.locInfo.size(); i++) {
            model.addElement(i);
        }
        selectionCB.setModel(model);
        selectionCB.setSelectedIndex(0);

        displayP.setLayout(new BorderLayout());
        displayP.add(imgP, BorderLayout.CENTER);

        imgP.addMouseMotionListener(new MouseMotionAdapter() {

            @Override
            public void mouseMoved(MouseEvent me) {
                // System.out.println("Event: " + me);
                double x = (double) me.getPoint().x / (double) imgP.getWidth();
                double y = 1.0 - (double) me.getPoint().y / (double) imgP.getHeight();

                double v = dp.getValueAt(x, y, selectionCB.getSelectedIndex());

                valueL.setText("" + v);
            }
        });

        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayP = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        selectionCB = new javax.swing.JComboBox();
        refreshB = new javax.swing.JButton();
        valueL = new javax.swing.JLabel();
        xCountS = new javax.swing.JSpinner();
        yCountS = new javax.swing.JSpinner();
        resetCountsB = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.layout.GroupLayout displayPLayout = new org.jdesktop.layout.GroupLayout(displayP);
        displayP.setLayout(displayPLayout);
        displayPLayout.setHorizontalGroup(
            displayPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 915, Short.MAX_VALUE)
        );
        displayPLayout.setVerticalGroup(
            displayPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 451, Short.MAX_VALUE)
        );

        selectionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionCBActionPerformed(evt);
            }
        });

        refreshB.setText("Refresh");
        refreshB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBActionPerformed(evt);
            }
        });

        xCountS.setToolTipText("X");
        xCountS.setName("X"); // NOI18N

        resetCountsB.setText("Refactor");
        resetCountsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetCountsBActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(selectionCB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(refreshB)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 324, Short.MAX_VALUE)
                        .add(valueL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 219, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(xCountS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(yCountS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(53, 53, 53)
                        .add(resetCountsB)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(valueL)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(selectionCB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(refreshB))
                        .add(xCountS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(yCountS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(resetCountsB)
                                .add(jButton1)))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, displayP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(displayP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionCBActionPerformed
        imgP.repaint();
    }//GEN-LAST:event_selectionCBActionPerformed

    private void refreshBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBActionPerformed
        imgP.repaint();
    }//GEN-LAST:event_refreshBActionPerformed

    private void resetCountsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetCountsBActionPerformed
        dp.setxCount((Integer)xCountS.getValue(), false);
        dp.setyCount((Integer)yCountS.getValue(), true);
    }//GEN-LAST:event_resetCountsBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DataDisplayPopup(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayP;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton refreshB;
    private javax.swing.JButton resetCountsB;
    private javax.swing.JComboBox selectionCB;
    private javax.swing.JLabel valueL;
    private javax.swing.JSpinner xCountS;
    private javax.swing.JSpinner yCountS;
    // End of variables declaration//GEN-END:variables
}
