/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImageViewer.java
 *
 * Created on Aug 25, 2011, 4:56:35 PM
 */
package edu.cmu.ri.airboat.enduser;

import edu.cmu.ri.airboat.floodtest.*;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import javax.swing.JPanel;

/**
 *
 * @author pscerri
 */
public class ImageViewer extends javax.swing.JFrame {
    private final BufferedImage img;

    /** Creates new form ImageViewer */
    public ImageViewer(BufferedImage img) {
        initComponents();
        this.img = img;
        
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(new ShowImageP(), BorderLayout.CENTER);
        setSize(img.getWidth() + 24, img.getHeight() + 24);
        
        System.out.println("Setting size to " + (img.getWidth() + 24) + " " + (img.getHeight() + 24));
        
        //pack();        
    }

    public class ShowImageP extends JPanel {
        
        public void paint(Graphics g) {
            g.drawImage(img, 0, 0, null);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 904, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 726, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
