/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CameraPanel.java
 *
 * Created on Apr 6, 2011, 8:34:21 PM
 */

package edu.cmu.ri.airboat.client.gui;

import edu.cmu.ri.crw.AsyncVehicleServer;
import edu.cmu.ri.crw.FunctionObserver;
import edu.cmu.ri.crw.FunctionObserver.FunctionError;
import edu.cmu.ri.crw.ImageListener;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author pkv
 */
public class CameraPanel extends AbstractAirboatPanel {

    /** Creates new form CameraPanel */
    public CameraPanel() {
        initComponents();
    }

    @Override
    public void setVehicle(AsyncVehicleServer vehicle) {
        super.setVehicle(vehicle);
        vehicle.addImageListener(new ImageListener() {

            public void receivedImage(byte[] imageData) {
                // Take a picture, and put the resulting image into the panel
                try {
                    BufferedImage image = ImageIO.read(new java.io.ByteArrayInputStream(imageData));
                    if (image != null) {
                        Image scaledImage = image.getScaledInstance(pictureLabel.getWidth(), pictureLabel.getHeight(), Image.SCALE_DEFAULT);
                        pictureLabel.setIcon(new ImageIcon(scaledImage));
                        CameraPanel.this.repaint();
                    } else {
                        System.err.println("Failed to decode image.");
                    }
                } catch (IOException ex) {
                    System.err.println("Failed to decode image: " + ex);
                }

            }
        }, null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        stopCaptureButton = new javax.swing.JButton();
        startCaptureButton = new javax.swing.JButton();
        pictureLabel = new javax.swing.JLabel();
        captureButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        stopCaptureButton.setText("Stop Capturing");
        stopCaptureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopCaptureButtonActionPerformed(evt);
            }
        });

        startCaptureButton.setText("Start Capturing");
        startCaptureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startCaptureButtonActionPerformed(evt);
            }
        });

        pictureLabel.setBackground(java.awt.Color.lightGray);
        pictureLabel.setOpaque(true);

        captureButton.setText("Take Water Sample");
        captureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captureButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pictureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addComponent(captureButton, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addComponent(stopCaptureButton, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addComponent(startCaptureButton, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startCaptureButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopCaptureButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(captureButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startCaptureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startCaptureButtonActionPerformed

        if (_vehicle == null)
            return;

        startCaptureButton.setEnabled(false);
        startCaptureButton.setSelected(true);

        _vehicle.startCamera(1, 2.0, 640, 480, new FunctionObserver<Void>() {

            public void completed(Void v) {
                startCaptureButton.setBackground(Color.GREEN);
                startCaptureButton.setOpaque(true);
                
                startCaptureButton.setEnabled(true);
                startCaptureButton.setSelected(false);
            }

            public void failed(FunctionError fe) {
                startCaptureButton.setBackground(Color.PINK);
                startCaptureButton.setOpaque(true);
                
                startCaptureButton.setEnabled(true);
                startCaptureButton.setSelected(false);
            }
        });
    }//GEN-LAST:event_startCaptureButtonActionPerformed

    private void stopCaptureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopCaptureButtonActionPerformed

        if (_vehicle == null)
            return;

        stopCaptureButton.setEnabled(false);
        stopCaptureButton.setSelected(true);

        _vehicle.stopCamera(new FunctionObserver<Void>() {

            public void completed(Void v) {
                stopCaptureButton.setBackground(Color.GREEN);
                stopCaptureButton.setOpaque(true);
                
                stopCaptureButton.setEnabled(true);
                stopCaptureButton.setSelected(false);
            }

            public void failed(FunctionError fe) {
                stopCaptureButton.setBackground(Color.PINK);
                stopCaptureButton.setOpaque(true);
                
                stopCaptureButton.setEnabled(true);
                stopCaptureButton.setSelected(false);
            }
        });
    }//GEN-LAST:event_stopCaptureButtonActionPerformed

    private void captureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captureButtonActionPerformed
        
        if (_vehicle == null)
            return;

        captureButton.setEnabled(false);
        captureButton.setSelected(true);

        _vehicle.captureImage(640, 480, new FunctionObserver<byte[]>() {

            public void completed(byte[] result) {
                captureButton.setBackground(Color.GREEN);
                captureButton.setOpaque(true);
                
                captureButton.setEnabled(true);
                captureButton.setSelected(false);
            }

            public void failed(FunctionError fe) {
                captureButton.setBackground(Color.PINK);
                captureButton.setOpaque(true);
                
                captureButton.setEnabled(true);
                captureButton.setSelected(false);
            }
        });
    }//GEN-LAST:event_captureButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton captureButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JButton startCaptureButton;
    private javax.swing.JButton stopCaptureButton;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void update() {
        // No updates required here!
    }

}
