/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataViewF.java
 *
 * Created on Apr 12, 2011, 9:15:28 PM
 */

package edu.cmu.ri.airboat.gulfsim.tasking.pollution;

import gov.nasa.worldwind.geom.Angle;
import gov.nasa.worldwind.geom.coords.UTMCoord;
import gov.nasa.worldwind.layers.RenderableLayer;
import java.awt.BorderLayout;
import java.awt.GraphicsConfiguration;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Transparency;
import java.awt.image.BufferedImage;

/**
 * 
 * @author pscerri
 */
public class DataViewF extends javax.swing.JFrame {

    DataModelViewerP vp = null;
    
    /** Creates new form DataViewF */
    public DataViewF() {
        initComponents();
        
        vp = new DataModelViewerP(new PollutionModel(), 
                UTMCoord.fromLatLon(Angle.fromDegrees(22.0), Angle.fromDegrees(-95)), 
                UTMCoord.fromLatLon(Angle.fromDegrees(27.0), Angle.fromDegrees(-86)));
                
        viewP.setLayout(new BorderLayout());
        viewP.add(vp, BorderLayout.CENTER);
        
        pack();
        setSize(500, 500);
        setVisible(true);
    }        
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewP = new javax.swing.JPanel();
        viewC = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.layout.GroupLayout viewPLayout = new org.jdesktop.layout.GroupLayout(viewP);
        viewP.setLayout(viewPLayout);
        viewPLayout.setHorizontalGroup(
            viewPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 872, Short.MAX_VALUE)
        );
        viewPLayout.setVerticalGroup(
            viewPLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 615, Short.MAX_VALUE)
        );

        viewC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ground truth", "Centralized GA" }));
        viewC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(viewP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(viewC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(16, 16, 16)
                .add(viewC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(viewP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCActionPerformed
        System.out.println("Value now " + viewC.getModel().getSelectedItem());
        String arg = (String)viewC.getModel().getSelectedItem();
        if (arg.equalsIgnoreCase("Ground truth")) {
            vp.setModel(new PollutionModel());
        } else if (arg.equalsIgnoreCase("Centralized GA")) {
            vp.setModel(new CentralizedGAPollutionModel());
        }
    }//GEN-LAST:event_viewCActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataViewF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox viewC;
    private javax.swing.JPanel viewP;
    // End of variables declaration//GEN-END:variables

}
